spring:
  application:
    name: product-service
server:
  tomcat:
    threads:
      max: 15
rating:
  service:
    endpoint: http://localhost:9090/ratings
resilience4j:
  bulkhead:
    instances:
      ratingService:
        maxConcurrentCalls: 10 # controls how many threads can enter the method concurrently.
        maxWaitDuration: 10ms # controls how long a request waits before failing (0 means fail immediately if the limit exceeded).
